CREATE TABLE join_a (year STRING, temp INT, quality INT)
  ROW FORMAT DELIMITED FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INPATH '${WEATHER_DATA}' OVERWRITE INTO TABLE join_a;

CREATE TABLE join_b (year STRING, temp INT, quality INT)
  ROW FORMAT DELIMITED FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INPATH '${WEATHER_DATA}' OVERWRITE INTO TABLE join_b;

SELECT * FROM join_a a JOIN join_b b ON a.temp = b.temp;